config/routes.rb
Rss::Application.routes.draw do
  devise_for :users, :controllers => { 
    :omniauth_callbacks => "users/omniauth_callbacks",
    :registrations => "registrations"
    },
    :path => '',
    :path_names => {
        :sign_up  => 'signup',
        :sign_in  => 'login',
        :sign_out => 'logout'
  }

  resources :users, :only => [:feed, :index, :edit, :destroy]
  resources :subscriptions
  resources :channels

  authenticated do
    root :to => redirect("/feed")
  end

  root :to => 'welcome#index'

  devise_scope :user do
    match "profile"       => "devise/registrations#edit", :as => :edit_user_registration
    match "feed"          => "users#feed",                :as => :feed
    match "favorites"     => "users#favorites",           :as => :favorites
  end

end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  attr_accessible :title, :user_id, :channel_id
  validates :title,  presence: true, length: { maximum: 100 }

  belongs_to :channel
  belongs_to :user
end

app/controllers/subscriptions_controller.rb
# coding: utf-8
class SubscriptionsController < ApplicationController
  before_filter :authenticate_user!

  def index
    @subscriptions = current_user.subscriptions
    if @subscriptions == []
      flash[:notice] = t("subscriptions.alerts.subscribe_any_channel")
    end
    sub_ids = @subscriptions.map(&:channel_id)
    @channels = []
    all_channels = Channel.all
    all_channels.each do |channel|
      @channels << channel unless sub_ids.include? channel.id
    end
  end

  def create
    current_subscriptions_amount = current_user.subscriptions.length
    if current_subscriptions_amount < User::MAX_SUBSCRIPTIONS[current_user.role]
      if params[:channel_id]
        channel_id = params[:channel_id]
        channel = Channel.find(channel_id)
        Subscription.create(:title => channel.title,
                         :user_id => current_user.id,
                         :channel_id => channel_id )
      end
    else
      flash[:notice] = t('subscriptions.alerts.account_limitations')
    end
    redirect_to subscriptions_path
  end

  def edit
    if params[:id] && params[:new_title]
      subscription = Subscription.find(params[:id])
      subscription.title = params[:new_title]
      subscription.save
    end
    redirect_to subscriptions_path
  end

  def destroy
    if params[:id]
      Subscription.find(params[:id]).destroy
    end
    redirect_to subscriptions_path
  end

end

app/helpers/subscription_helper.rb
module SubscriptionHelper
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/subscriptions/index.html.haml
.body-content
  .subscriptions-manager
    .suggest
      = t('subscriptions.suggest_title')
      = form_tag channels_path do
        = text_field_tag :channel_url
        = submit_tag t('subscriptions.suggest_button')
    %h1= t("subscriptions.subscriptions")
    - if @subscriptions == []
      = t('subscriptions.no_subscriptions')
    %ul.subscriptions
      - @subscriptions.each do |subscription|
        %li
          = form_tag  subscription_path(subscription), |
            :action => :delete,                        |
            :method => :delete ,                       |
            :style => "display:inline"  do             |
            = submit_tag subscription.title, :class => ""
          = form_tag edit_subscription_path(subscription), |
            :action => :edit,                              |
            :class => "edit-channels-title-form",          |
            :style => "display:none",                      |
            :method => :get do                             |
            = text_field_tag :new_title, subscription.title
          %span.edit-channel-title
    %h1= t('subscriptions.available_channels')
    - if @channels.each == []
      = t('subscriptions.no_available_channels')
    %ul.channels
      - @channels.each do |channel|
        %li
          = form_tag subscriptions_path,   |
            :action => :create,            |
            :method => :post,              |
            :style => "display:inline"  do |
            = hidden_field_tag :channel_id, channel.id
            = submit_tag channel.title