config/routes.rb
Rss::Application.routes.draw do
  devise_for :users, :controllers => { 
    :omniauth_callbacks => "users/omniauth_callbacks",
    :registrations => "registrations"
    },
    :path => '',
    :path_names => {
        :sign_up  => 'signup',
        :sign_in  => 'login',
        :sign_out => 'logout'
  }

  resources :users, :only => [:feed, :index, :edit, :destroy]
  resources :subscriptions
  resources :channels

  authenticated do
    root :to => redirect("/feed")
  end

  root :to => 'welcome#index'

  devise_scope :user do
    match "profile"       => "devise/registrations#edit", :as => :edit_user_registration
    match "feed"          => "users#feed",                :as => :feed
    match "favorites"     => "users#favorites",           :as => :favorites
  end

end

app/views/layouts/_alerts.html.haml
%div{:class => "notice #{"hidden" unless notice}"}
  = notice
%div{:class => "alert #{"hidden" unless alert}"}
  = alert

app/views/layouts/_navigation.html.haml
= link_to "Atom Reader",  root_path, :class=> 'brand'
- if user_signed_in?
  = link_to "", :destroy_user_session, :method => :delete, :title => t('navigation.logout_hint'), :class =>"glyph logout"
  = link_to "", :edit_user_registration, :title=> t('navigation.user_settings_hint'), :class =>"glyph user"
  = link_to "", subscriptions_path, :title => t("navigation.subscriptions_hint"), :class => "glyph channels"
  %a.glyph.fav{:href => "/favorites", :title => t('navigation.favorites_hint')}
  = form_tag :feed, :method => "get", :class => "glyph search" do
    = text_field_tag :search, params[:search], :placeholder => t('navigation.search_hint')
- else
  - if devise_mapping.registerable? && controller_name != 'registrations' && controller_name != 'users'
    = link_to "", new_registration_path(resource_name), :class => "glyph signup", :title => t('navigation.signup')
  = link_to "", user_omniauth_authorize_path(:google_oauth2), :class => "glyph googleplus", :title => t('navigation.google_signup')

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=utf-8", "http-equiv" => "Content-Type"}
      %title Rss
      = stylesheet_link_tag    "application", :media => "all"
      = javascript_include_tag "application"
      = csrf_meta_tags
  %body
    %nav
      .content
        = render 'layouts/navigation'
    .body
      = render 'layouts/alerts'
      = yield